const menu = [
  {
    id: 1,
    title: 'buttermilk pancakes',
    category: 'breakfast',
    price: 15.99,
    img: './images/item-1.jpeg',
    desc: `Light, soft and fluffy with the perfect balance of sweet, salty and tang; you may not even want them smothered in syrup! `,
  },
  {
    id: 2,
    title: 'diner double',
    category: 'lunch',
    price: 13.99,
    img: './images/item-2.jpeg',
    desc: `Two hand-pressed beef patties, topped with melted American cheese, caramelized onions, and All-American sauce, all sandwiched between two brioche buns `,
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'shakes',
    price: 6.99,
    img: './images/item-3.jpeg',
    desc: `A sweet beverage made by blending milk, ice cream, and flavorings or sweeteners such as butterscotch, caramel sauce, chocolate syrup, fruit syrup, or whole fruit into a thick, sweet, cold mixture `,
  },
  {
    id: 4,
    title: 'country delight',
    category: 'breakfast',
    price: 20.99,
    img: './images/item-4.jpeg',
    desc: `The full English breakfast consists of fried eggs, sausages, back bacon, tomatoes, mushrooms, fried bread and often a slice of white or black pudding `,
  },
  {
    id: 5,
    title: 'GiantHum',
    category: 'lunch',
    price: 22.99,
    img: './images/item-5.jpeg',
    desc: `Juicy, mouthwatering, tasty, and everything you’d ever want to savor `,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'shakes',
    price: 18.99,
    img: './images/item-6.jpeg',
    desc: `This classic Oreo mousse is light and it will rival your favorite French restaurant's version`,
  },
  {
    id: 7,
    title: 'bacon overflow',
    category: 'breakfast',
    price: 8.99,
    img: './images/item-7.jpeg',
    desc: `For the breakfast meat lover. 2 eggs, bacon, sausage, ham, toast, and breakfast potatoes (no substitutions please)
 `,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'lunch',
    price: 12.99,
    img: './images/item-8.jpeg',
    desc: `Traditional american lunch - hamburger and potato free  `,
  },
  {
    id: 9,
    title: 'sandwich',
    category: 'shakes',
    price: 16.99,
    img: './images/item-9.jpeg',
    desc: `Basic form, slices of meat, cheese, or other food placed between two slices of bread `,
  },
];
export default menu;